services:

  fdp:
    image: fairdatasystems/fdp:2026-02-11
    restart: always
    hostname: fdp
    volumes:
      - ./fdp/application-{PREFIX}.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
      - graphdb
    networks:
      - {PREFIX}-default


  # FAIR Data Point client
  fdp_client:
    image: fairdatasystems/fdpclient:2026-02-11
    hostname: fdpclient
    restart: always
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp/assets:/usr/share/nginx/html/assets:ro
      - ./fdp/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - {FDP_PORT}:80  # You should/must close this port, if you are using hitch
    command: ./start.sh 
    networks:
      - {PREFIX}-default


  graphdb:
    image: fairdatasystems/gdb:2026-02-11
    restart: always
    hostname: graphdb
    ports:
      - 127.0.0.1:{GDB_PORT}:7200
    volumes:
      - {PREFIX}-graphdb:/opt/graphdb/home
    networks:
      - {PREFIX}-default

      
  # Mongo for FDP server    
  mongo:
    image: fairdatasystems/mdb:2026-02-11
    hostname: mongo
    restart: always
    volumes:
      - {PREFIX}-mongo-data:/data/db
      - {PREFIX}-mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - {PREFIX}-default


volumes:
  {PREFIX}-graphdb:
    external: true
  {PREFIX}-mongo-data:
    external: true
  {PREFIX}-mongo-init:
    external: true
  {PREFIX}-fdp-server:
    external: true

networks:
  {PREFIX}-default:
